[project]
name = "song-year-guesser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.1.0",
    "requests>=2.32.5",
    "streamlit>=1.52.2",
    "streamlit-autorefresh>=1.0.1",
    "watchdog>=6.0.0",
]
