[project]
name = "song-year-guesser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pillow>=10.0.0",
    "requests>=2.31.0",
    "streamlit==1.41.1",
    "streamlit-autorefresh>=1.0.1",
]
